[build]
builder = "nixpacks"
buildCommand = "npm install --ignore-scripts && npm run build"
nixpacksConfigPath = "nixpacks.toml"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10 